# Generated by Django 4.2.7 on 2023-12-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stockpricedata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Date",
                    models.DateField(
                        blank=True, default="DEFAULT VALUE", max_length=100, null=True
                    ),
                ),
                (
                    "Open",
                    models.FloatField(
                        blank=True, default="DEFAULT VALUE", max_length=140, null=True
                    ),
                ),
                (
                    "High",
                    models.FloatField(
                        blank=True, default="DEFAULT VALUE", max_length=140, null=True
                    ),
                ),
                (
                    "Close",
                    models.FloatField(
                        blank=True, default="DEFAULT VALUE", max_length=140, null=True
                    ),
                ),
                (
                    "AdjustedClose",
                    models.FloatField(
                        blank=True, default="DEFAULT VALUE", max_length=140, null=True
                    ),
                ),
                (
                    "Volume",
                    models.BigIntegerField(
                        blank=True, default="DEFAULT VALUE", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tickersymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("tickerName", models.CharField(max_length=1000)),
            ],
        ),
    ]
