# Generated by Django 4.2.7 on 2023-12-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockwebsite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpricedata",
            name="Low",
            field=models.FloatField(blank=True, max_length=140, null=True),
        ),
    ]
