# Generated by Django 4.2.7 on 2023-12-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockwebsite", "0002_stockpricedata_low"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpricedata",
            name="ticker",
            field=models.CharField(
                blank=True, default="DEFAULT VALUE", max_length=20, null=True
            ),
        ),
    ]
